import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={sora.className}>
				<div className=" min-h-screen max-w-screen bg-[#0F0F0F] text-white">
					<Navbar />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
